---
title: "Mini-Project 4"
author: "Eleanor Ewing, Max Ranieri, Farah Samawi"
date: "12/02/2017"
output: 
  html_document:
    code_folding: hide
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(mdsr)
library(RMySQL)
library(readr)
library(RColorBrewer)
```

```{r}
# Connect to IMDb
db <- dbConnect_scidb(dbname = "imdb")

# Get genre info
query_genre <- 
  "SELECT movie_id, 
    COUNT(CASE WHEN info_type_id = 3 THEN info ELSE NULL END) AS genres,
    production_year
  FROM imdb.movie_info
  LEFT JOIN title ON movie_info.movie_id = title.id
  WHERE kind_id = 1 AND 
    production_year IS NOT NULL AND 
    production_year > 1909 AND production_year < 2018 AND
    info IS NOT NULL AND 
    movie_id IN (SELECT movie_id
                  FROM movie_info
                  WHERE info_type_id = 8 AND 
                  info LIKE '%USA%')
  GROUP BY movie_id;"

genre_data <- db %>%
  dbGetQuery(query_genre) 

# Get gross info
query_gross <- 
  "SELECT movie_id, 
    info AS gross
  FROM imdb.movie_info
  LEFT JOIN title ON movie_info.movie_id = title.id
  WHERE kind_id = 1 AND 
    production_year IS NOT NULL AND
    info_type_id = 107"
  
gross_data <- db %>%
  dbGetQuery(query_gross)

# Get user rating info
query_rating <-
  "SELECT movie_id, 
    info AS rating
  FROM imdb.movie_info_idx
  LEFT JOIN title ON movie_info_idx.movie_id = title.id
  WHERE kind_id = 1 AND
    production_year IS NOT NULL AND
    info_type_id = 101 AND
    info IS NOT NULL;"

rating_data <- db %>%
  dbGetQuery(query_rating)
```

```{r}
# Determine average number of genres per year
genres_by_year <- genre_data %>%
  group_by(production_year) %>%
  summarize(mean = mean(genres))

# Plotting year vs. average number of genres
ggplot(genres_by_year, aes(x = production_year, y = mean)) +
  geom_line(col = "white") +
  geom_vline(aes(xintercept=1948), col="red") +
  labs(x = "Year", y = "Average genre multiplicity") +
  theme_dark() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```

```{r}
# Join genre data with gross data
movie_data <- left_join(gross_data, genre_data, by = "movie_id") %>% 
  na.omit()

# Helper function to convert string into number for gross column
numberize <- function(str) {
  parse_number(sub(" .*", "", str))
}

# Filtering gross to usable form and preparing to plot
movie_data <- movie_data %>%
  filter(substr(gross, 1, 1) == "$") %>%
  filter(grepl("*\\(USA\\)*", gross)) %>%
  mutate(gross = numberize(gross)) %>%
  group_by(movie_id) %>%
  # can we summarize in a less hacky way?
  summarize(gross = max(gross), genres = max(genres), production_year = max(production_year))

# remove 0's, ie, 0 genres listed, 0 gross profit, etc. 
row_sub = apply(movie_data, 1, function(row) all(row !=0 ))
movie_data <- movie_data[row_sub,]
```

```{r}
ggplot(movie_data, aes(x = production_year, y = genres, col = gross )) +
  geom_jitter(alpha = 0.1)
```

```{r}
movie_data2 <- left_join(rating_data, genre_data, by = "movie_id") %>% 
  na.omit()

movie_data2 <- movie_data2 %>%
  mutate(rating = parse_number(rating))
```

```{r}
ggplot(movie_data2, aes(x = production_year, y = rating, color = genres, size = genres)) +
  scale_colour_gradient(low = "white", high = "black", na.value = "red", guide = "colorbar") +
  geom_jitter(shape = 1) +
  theme_dark()
```

```{r}
movie_data2 <- movie_data2 %>%
  mutate(genres =
    ifelse(genres < 4,
      1,
      ifelse(genres < 6,
        2,
        3
        )
      )
  )
```

```{r}
row_sub = apply(movie_data2, 1, function(row) all(row !=0 ))
movie_data2 <- movie_data2[row_sub,]

movie_data2 <- movie_data2 %>%
  group_by(genres, production_year) %>%
  summarize(rating = mean(rating))

spectral2 = brewer.pal(4, "Spectral")

ggplot(movie_data2, aes(x = production_year, y = rating, color=factor(genres))) +
  #geom_ribbon(aes(ymin = 0, ymax = rating), alpha = 0.3) +
  geom_line(alpha = 0.8) +
  scale_color_manual(values = spectral2, 
                     labels = c("1-3", "4-6", "7+"), 
                     name = "Genres") +
  theme_dark() +
  labs(x = "Year", y = "User rating") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```